- ros_topic_name: /gwm/sensors/front_depth/image_raw
  gz_topic_name: /depth_camera
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
  publisher_queue: 8
  subscriber_queue: 8
  qos_profile: SENSOR_DATA
  lazy: false
- ros_topic_name: /gwm/sensors/front_depth/camera_info
  gz_topic_name: /camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
  publisher_queue: 8
  subscriber_queue: 8
  qos_profile: SENSOR_DATA
  lazy: false
